[theme]
# Primary accent color for interactive elements.
primaryColor = "#d33682"

# Background color for the main content area.
backgroundColor = "#004548ff"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#064bc2ff"

# Color used for almost all text.
textColor = "#fff"

[client]
toolbarMode = "minimal"